//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources_department.Enter.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchebnayaPractika1Entities : DbContext
    {
        public UchebnayaPractika1Entities()
            : base("name=UchebnayaPractika1Entities")
        {
        }
        private static UchebnayaPractika1Entities _context;

        public static UchebnayaPractika1Entities GetContext()
        {
            if (_context == null)
                _context = new UchebnayaPractika1Entities();
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Human> Human { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Suspended> Suspended { get; set; }
        public virtual DbSet<Аккаунт> Аккаунт { get; set; }
    }
}
