//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources_department.Enter.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аккаунт
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNum { get; set; }
        public string Password { get; set; }
        public Nullable<int> IDRole { get; set; }
        public Nullable<int> Human_ID { get; set; }
    
        public virtual Human Human { get; set; }
        public virtual Role Role { get; set; }
    }
}
